export const bookingPolicies = [
  "Durasi minimal 1 jam dan maksimal 8 jam per sesi.",
  "Pengajuan bisa dilakukan hingga H-30 dari tanggal acara.",
  "Slot yang berstatus approved tidak dapat dipilih ulang.",
  "Surat pengajuan wajib dilampirkan dalam format PDF, DOC, atau DOCX.",
  "Admin dapat menolak jika agenda, kapasitas, atau kebutuhan teknis tidak sesuai.",
];

export const roomSeeds = [
  {
    slug: "feb-meeting-room",
    name: "Ruang Rapat Bisnis Digital",
    shortName: "Ruang Rapat BD",
    capacity: 20,
    summary: "Ruang rapat hangat untuk koordinasi cepat, presentasi kecil, dan diskusi pimpinan.",
    description:
      "Dirancang untuk pertemuan formal dengan suasana fokus. Layout fleksibel untuk rapat meja bundar, coaching session, atau presentasi internal dengan kebutuhan teknis ringan.",
    floor: "Lantai 2 Area Program Studi Bisnis Digital",
    hours: "08.00 - 20.00 WIB",
    notice: "Disarankan ajukan minimal H-2 untuk kebutuhan konsumsi dan layout khusus.",
    responseTime: "< 4 jam kerja",
    popularity: "Paling sering dipakai staf & dosen",
    amenities: [
      "Proyektor 4K",
      "Smart TV 65 inci",
      "Whiteboard kaca",
      "Conference speaker",
      "AC sentral",
      "Pantry corner",
    ],
    idealFor: ["Rapat pimpinan", "Sidang kecil", "Presentasi internal", "Interview panel"],
    theme: "from-[#0f2f5f] via-[#1d4f91] to-[#4da3ff]",
    glow: "bg-[#4da3ff]/30",
    accent: "#1d4f91",
  },
  {
    slug: "seminar-room",
    name: "Auditorium Bisnis Digital",
    shortName: "Auditorium BD",
    capacity: 600,
    summary: "Aula utama berkapasitas besar untuk seminar, kuliah umum, dan peluncuran program kampus.",
    description:
      "Ruang skala besar dengan tata cahaya panggung, sound system, dan sirkulasi audiens yang cocok untuk agenda publik berskala fakultas maupun universitas.",
    floor: "Lantai 1 Area Program Studi Bisnis Digital",
    hours: "07.00 - 21.00 WIB",
    notice: "Agenda eksternal wajib melampirkan rundown dan PIC teknis saat pengajuan.",
    responseTime: "1 hari kerja",
    popularity: "Favorit untuk acara besar kampus",
    amenities: [
      "Panggung modular",
      "Sound system auditorium",
      "Layar LED utama",
      "Ruang kontrol",
      "Mic wireless",
      "Akses kursi roda",
    ],
    idealFor: ["Seminar nasional", "Kuliah tamu", "Talkshow", "Wisuda internal"],
    theme: "from-[#0b3b6e] via-[#1565c0] to-[#38bdf8]",
    glow: "bg-[#38bdf8]/30",
    accent: "#1565c0",
  },
];

export const sampleBookings = [
  {
    bookingCode: "BK-240427-01",
    roomSlug: "feb-meeting-room",
    borrower: "Nadia Putri",
    email: "nadia.putri@kampus.ac.id",
    organization: "Program Studi Bisnis Digital",
    purpose: "Koordinasi akreditasi dan pembagian tugas asesor",
    status: "pending" as const,
    startTime: "2026-04-28T10:30:00+07:00",
    endTime: "2026-04-28T12:00:00+07:00",
    attendees: 12,
    requestLetterName: "surat-pengajuan-prodi-manajemen.pdf",
  },
  {
    bookingCode: "BK-240427-02",
    roomSlug: "seminar-room",
    borrower: "Himpunan Mahasiswa Bisnis Digital",
    email: "sekretariat@bisnisdigital.ac.id",
    organization: "Himpunan Mahasiswa Bisnis Digital",
    purpose: "Kuliah umum dan panel diskusi ekonomi kreatif",
    status: "approved" as const,
    startTime: "2026-04-29T10:30:00+07:00",
    endTime: "2026-04-29T16:30:00+07:00",
    attendees: 420,
    requestLetterName: "surat-pengajuan-hima-bisnis-digital.pdf",
  },
  {
    bookingCode: "BK-240427-03",
    roomSlug: "feb-meeting-room",
    borrower: "Dian Arif",
    email: "dian.arif@kampus.ac.id",
    organization: "UPT Kerja Sama",
    purpose: "Presentasi vendor dan evaluasi kebutuhan sistem",
    status: "rejected" as const,
    startTime: "2026-04-30T13:00:00+07:00",
    endTime: "2026-04-30T15:00:00+07:00",
    attendees: 16,
    requestLetterName: "surat-pengajuan-upt-kerjasama.docx",
  },
  {
    bookingCode: "BK-240427-04",
    roomSlug: "seminar-room",
    borrower: "Rahma Aulia",
    email: "rahma.aulia@kampus.ac.id",
    organization: "Career Center Bisnis Digital",
    purpose: "Townhall dan pemaparan program magang mitra",
    status: "pending" as const,
    startTime: "2026-04-30T17:00:00+07:00",
    endTime: "2026-04-30T20:00:00+07:00",
    attendees: 300,
    requestLetterName: "surat-pengajuan-career-center.pdf",
  },
];
